# Fixed version 1.4.8

It seems the only fix was to remove the options the start a runner server from the CLI, as can be seen in [this](https://github.com/bentoml/BentoML/commit/42f937f90319cbc794274ca69d48df12f4aa1180) commit.

The deserialization code hasn't changed (verified with 1.4.8).

Instead of running the following command (taken from `vulnerable/Dockerfile`)

``` sh
bentoml start-runner-server --runner-name mymodel --working-dir . --host 0.0.0.0 --port 3000
```

we can now run

``` sh
python3 -m bentoml_cli._internal.start start-runner-server --runner-name mymodel --working-dir . --host 0.0.0.0 --port 3000
```

and launch the same exploit as described for the "vulnerable" version.
